### ISSUE TITLE
[Feature] 알림, 원스와의 대화 페이지 구현 

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#11]
### 🚀 Feature
> `알림`, `원스와의 대화` 페이지 구현 

<p align="center">
  <img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/871aa0aa-bf73-4a2d-9e6a-6e038cfd1f18" width="200" />
  <img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/db719b77-b40e-4928-957b-0d906f44b755" width="200"/>
</p>

### ✅ Tasks
- [x] 알림 타입마다 위젯 나누기
- [x] 새로운 알림 구분
- [x] 원스와의 대화 페이지 UI 구현
- [x] 스크롤 구현
