### ISSUE TITLE
[Feature] 로그인 및 회원가입 페이지 구현

### ISSUE THREAD

**Issue by jiminnee** [EWHA-LUX/ONCE-FE#14]
### 🚀 Feature
> 앱 초기화면 및 로그인 페이지 구현
<p align="center">
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/2e8d25e7-4ea3-4168-a1c1-856657b0c1a6" width="200"/>
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/85f646d3-cddb-4ca1-8d6c-c07020fc18e26" width="200"/>
</p>
<p align="center">
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/a3726185-ff71-4453-83df-f46bcefb35d4" width="200"/>
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/c114d846-bcf9-41f5-9fc5-3b1b0ffb5a61" width="200"/>
</p>
<p align="center">
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/ba873aa6-0da1-4114-8eb7-88e2093ef691" width="200"/>
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/109728087/57ac9d82-d5db-4d39-896d-e4e0642e817b" width="200"/>
</p>

### ✅ Tasks
1) 앱 초기화면
- [x] 앱 초기화면 뷰 구현

2) 로그인
- [x] 로그인 페이지 뷰 구현
- [x] 아이디 및 비밀번호 키패드 입력
- [x] 로그인, 회원가입, ID/PW 찾기 버튼

3) 회원가입
- [x] TextField 키패드 입력
- [x] TextField 숫자/글자 입력 여부 확인 & 길이 제한 적용
- [x] 비밀번호 일치 여부 체크 & 암호화

4) 카드 등록
- [x] 카드사 선택 시 해당 Container 색상 변경
- [x] 전체 카드사 버튼 클릭 시 전체 선택 기능 구현
- [x] 카드 검색창 구현
- [x] 연결 카드사 탭 구현 (한번에 한개의 탭만 선택 가능&index0번 탭은 처음에 무조건 선택되도록)
- [x] 카드 Container 선택 기능 (중복 선택 가능)
