### ISSUE TITLE
[Feature] 알림 페이지 팝업 구현

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#19]
### 🚀 Feature
> 알림 페이지 팝업 구현

<p align="center">
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/a558ef34-eee3-430a-a723-3b2bf9099c7e" width="200"/>
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/aa3130ba-13e6-425a-b169-3fca6507ed6d" width="200"/>
</p>
<p align="center">
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/1fefcf13-3a5f-4629-9062-9954eaf38641" width="200"/>
<img src="https://github.com/EWHA-LUX/ONCE-FE/assets/94354545/cac447c7-b11e-4860-b5f8-361597666772" width="200"/>
</p>

### ✅ Tasks
- [x] 팝업 타입 나누기
- [x] 알림 팝업 UI 구현
- [x] 지도 api 연결
