### ISSUE TITLE
[Feature & Style] 전반적인 스타일 수정

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#23]
### 🚀 Feature & 🎨 Style
> 설정 추가, 전반적인 스타일 수정

### ✅ Tasks
- [x] initialRoute 수정
- [x] iOS 구글맵 api 연결
- [x] 로그인 스타일 수정
- [x] 회원가입 step1 스타일 수정
- [x] 회원가입 step2 스타일 수정
- [x] 회원가입 step3 스타일 수정 (카드사 선택)
- [x] 회원가입 step4 스타일 수정 (카드 검색)
