### ISSUE TITLE
[Feature] 앱 로고 및 Splash Screen & 설정 화면 구현

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#25]
### 🚀 Feature
> 앱 로고, Splash Screen, 설정 화면

### ✅ Tasks
- [x] iOS 앱 로고
- [x] 안드로이드 앱 로고
- [x] 앱 이름 변경
- [x] iOS Splash Screen
- [x] 안드로이드 Splash Screen
- [x] 설정 화면 구현
