### ISSUE TITLE
[Fix] 화면 오버플로우 해결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#34]
### 🚀 Feature
> 화면 오버플로우 해결 

### ✅ Tasks
- [x] 챗봇 가격 입력 오버플로우 해결
- [x] 월별혜택조회 오버플로우 해결
- [x] 마이월렛 하단 오버플로우 해결
- [x] 원스와의 대화 오버플로우 해결
- [x] `Indicator` 스타일 통일시키기
