### ISSUE TITLE
[Feature] 챗봇 서버 연결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#35]
### 🚀 Feature
> 챗봇 서버 연결

### ✅ Tasks
- [x] 홈 화면 기본 정보 API 연결
- [ ] 챗봇 카드 추천 API 연결
- [ ] 로딩 화면 구현
- [ ] 챗봇 응답 말풍선 구현
- [ ] 결제 확인 화면 구현
- [ ] 결제 확인 API 연결
