### ISSUE TITLE
[Feature] 알림 서버 연결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#37]
### 🚀 Feature
> 알림 서버 연결

### ✅ Tasks
- [x] 알림 리스트 조회 API 연결
- [x] 데이터 로딩되는 화면 추가
- [x] 알림 상세 조회 API 연결
