### ISSUE TITLE
[Feature] 마이월렛 서버 연결

### ISSUE THREAD

**Issue by jiminnee** [EWHA-LUX/ONCE-FE#39]
### 🚀 Feature
> 마이월렛 서버 연결

### ✅ Tasks
- [x] 마이월렛 조회 API 연결
- [x] cardBanner 파일 삭제
- [x] card_item 코드 수정
- [x] 남은 실적 금액 세자리 수마다 콤마(,) 표시
