### ISSUE TITLE
[Feature] 원스와의 대화 서버 연결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#41]
### 🚀 Feature
> 원스와의 대화 서버 연결

### ✅ Tasks
- [x] 챗봇 대화 조회 API 연결
- [x] cardItem 파일 삭제
- [x] 대화 없는 경우 예외 처리
