### ISSUE TITLE
[Feature] 월별 혜택 조회 서버 연결

### ISSUE THREAD

**Issue by jiminnee** [EWHA-LUX/ONCE-FE#43]
### 🚀 Feature
> 월별 혜택 조회 서버 연결

### ✅ Tasks
- [x] 월별 혜택 조회 API 연결
- [x] path variable '현재 접속 월'로 초기화
- [x] 카테고리에 따른 아이콘 변경
