### ISSUE TITLE
[Fix] 오버플로우 해결 & 일부 페이지 수정

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#61]
### 🚀 Feature
> signup 오버플로우 해결 & 일부 페이지 수정

### ✅ Tasks
- [x] 회원가입 키보드 오버플로우 해결
- [x] 내 정보 수정하기 키보드 오버플로우 해결
- [x] 카드 검색 오버플로우 해결
- [x] 카드 전체 선택 해제 수정
- [x] 카드 이미지 가로로 통일
- [x] 마이월렛 페이지 닉네임 추가
- [x] 마이월렛 페이지 카드 방향 변경
- [x] 회원가입 birthday 입력 안 했을 때 생기는 오류 해결
