### ISSUE TITLE
[Feature] 카드 추천 API 연결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#64]
### 🚀 Feature
> 챗봇 서버 연결

### ✅ Tasks
1차
- [x] 홈 화면 기본 정보 API 연결
- [x] 챗봇 카드 추천 API 연결
- [x] 로딩 화면 구현
- [x] 챗봇 응답 말풍선 구현

2차
- [x] 결제 확인 화면 구현
- [x] 결제 확인 API 연결
- [x] 결제 여부 변경 스낵바 구현 

3차
- [x] 주카드인 경우 결제 여부 변경 말풍선 안 뜨도록
