### ISSUE TITLE
[Fix] 알림 오류 해결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#65]
### 🔧 Fix
> 알림 오류 해결

### ✅ Tasks
- [x] announceTodayList 비어있는 경우 체크
- [x] announcePastList 비어있는 경우 체크
- [x] '알림 없음' 문구 추가
