### ISSUE TITLE
[Feature] 로딩 화면 & 회원 탈퇴 & 비밀번호 변경

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#73]
### 🚀 Feature
> 로딩 화면 & 회원 탈퇴 & 비밀번호 변경

### ✅ Tasks
- [x] 로딩 화면 `spinkit` 추가
- [x] [설정] 회원 탈퇴 API 연결
- [x] [설정] 로그아웃 구현
- [x] 비밀번호 변경 뷰 구현
- [x] 비밀번호 변경 API 연결
