### ISSUE TITLE
[Feature] 앱 접속 시 주카드 실적 조회 및 기기 토큰 등록 구현

### ISSUE THREAD

**Issue by jiminnee** [EWHA-LUX/ONCE-FE#74]
### 🚀 Feature
> 앱 접속 시 주카드 실적 조회 및 기기 토큰 등록 구현

### ✅ Tasks
- [x] 주카드 실적 조회 서버 API 연결
- [x] android firebase 연동
- [x] 기기 토큰 등록 서버 API 연결
