### ISSUE TITLE
[Fix] 알림 페이지 오류 해결

### ISSUE THREAD

**Issue by Haewonny** [EWHA-LUX/ONCE-FE#78]
### 🔧 Feature
> 알림 구글맵 오류 해결

### ✅ Tasks
- [x] API key 재설정
- [x] 지도 안 보이는 오류 해결
- [x] percent indicator 퍼센트 계산 방식 변경
